#!/bin/bash

ip="85.17.1.95"
user="Egor"

output=$(git status --porcelain -sb)
if [[ "$output" != "## master...origin/master" ]]; then
    echo "!!! WARNING: repository is not synced"
    echo "$output"
    echo
    echo "Press Enter to continue."
    read
fi

ssh "$ip" -l "$user" bash -s -l <<<'
    cd tmux-autocomplete
    echo ":: Pulling repository"
    git config --global user.email "you@example.com"
    git config --global user.name "Your Name"
    git pull --rebase origin master || exit 1
    echo ":: Removing old packages"
    rm -rf pkg/
    echo ":: Making package"
    make pkg_osx || exit 2
    echo ":: Installing"
    sudo installer -pkg pkg/*_native.pkg -target / -verbose
'
