#!/bin/bash

ip="85.17.1.95"
user="Egor"

ssh "$ip" -l "$user" bash -s -l <<<'
    cd tmux-autocomplete
    echo ":: Pulling repository"
    git pull || exit 1
    echo ":: Removing old packages"
    rm -rf pkg/
    echo ":: Making package"
    make pkg_osx || exit 2
    echo ":: Installing"
    sudo installer -pkg pkg/*_native.pkg -target / -verbose
'
