#!/bin/bash

set -euo pipefail

cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
source ../vendor/github.com/reconquest/import.bash/import.bash

import:use "github.com/reconquest/test-runner.bash"

:cleanup() {
    :
}

:main() {
    trap :cleanup EXIT

    cd ..

    make build

    cd integration_tests

    test-runner:set-local-setup setup.sh
    test-runner:set-local-teardown teardown.sh
    test-runner:set-testcases-dir testcases

    test-runner:run "${@}"
}

:main "${@}"
